### ISSUE TITLE
Unable to navigate to subsequent Blackout pages

### ISSUE THREAD

**Issue by dakotacody** [alerta/alerta-webui#486] opened 2021-10-28 19:36 UTC
**Issue Summary**
When there are enough blackouts to require multiple pages in the Alerta UI the `+` button at the bottom right blocks the navigation to the next page

**Environment**
- OS:  Linux
- API version: 8.6.0 
- Deployment: self-hosted
- For self-hosted, WSGI environment: nginx/uwsgi

- Database:  Postgres

- Server config:
  Auth enabled? Yes
  Auth provider? saml2 (okta) 
  Customer views? No
  
- web UI version: 8.5.0

**To Reproduce**
1. Create enough blackouts to require more than 1 page
2. Click on  `blackouts` link 
3. Scroll down to  bottom right of the page to navigate to page 2 of blackouts
4. The issue is the yellow `+` for creating a blackout in the UI obstructs the navigation to the 2nd page

I realize that you can display more per page, but at least for me, this causes a load on my computer when loading many many items.   We'd like to keep some blackout information around for about a month before deleting it so potentially there could be a lot. 

For web app issues, include any web browser JavaScript console errors.

**Expected behavior**
The create button could be placed in a position that allows me to get to the underlying navigation link. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2693262/139324071-ea0be7a6-fc70-4076-aed4-36f2135ba8ab.png)

**Additional context**

NOTE: Please provide as much information about your issue as possible.
Failure to provide basic details about your specific environment make
it impossible to know if an issue has already been fixed, can delay a
response and may result in your issue being closed without a resolution.

**Comment by satterly** [comment] 2021-11-13 14:55
Duplicate of #450 Fixed by #470

**Closed by satterly** 2021-11-13 14:55 UTC
Labels: bug, priority: medium
