### ISSUE TITLE
Add notes to multiple alerts at the same time

### ISSUE THREAD

**Issue by aafuwape-tc** [alerta/alerta-webui#459] opened 2021-03-25 15:35 UTC
**Is your feature request related to a problem? Please describe.**
We use alerta to display alerts from multiple sources. Sometimes many of the alerts are related and therefore we would like to add a note to all the related alerts with the same ticket ID. At the moment, we need to add the ticket ID to each alert by first clicking on the alert and using the "ADD NOTE" button.
![image](https://user-images.githubusercontent.com/68665771/112499520-f06bbe80-8d5d-11eb-8705-e5cdf8a3ae96.png)

**Describe the solution you'd like**
A great solution will be a batch edit function. This can be achieved by adding a "ADD NOTE" button to the list of commands at the top of the screen. This way, multiple alerts can be selected at the same time and a note added.
![image](https://user-images.githubusercontent.com/68665771/112499299-b8fd1200-8d5d-11eb-821a-0eb674831a0a.png)

**Describe alternatives you've considered**
The alternative/workaround currently used is to click each alert and comment on them one by one which is inefficient.

**Comment by satterly** [comment] 2021-04-17 10:45
Duplicate of #369

**Closed by satterly** 2021-04-17 10:45 UTC
