### ISSUE TITLE
Allow changing the status comment without changing the current status

### ISSUE THREAD

**Issue by vykulakov** [alerta/alerta-webui#236] opened 2019-08-22 12:26 UTC
**Is your feature request related to a problem? Please describe.**
My proposal does not solve any problem but makes using Alerta more convenient from my point of view.

**Describe the solution you'd like**
Now I cannot change the status comment without changing the current status of an alert but in some cases, it may be necessary. For instance, if the previous comment is not correct or the new one contains additional information. As a result, now I should use the following sequence: change status from A to B and then change the status back from B to A with a new comment - no so elegant.

I don't have any idea how it may be implemented with minimal efforts. Maybe, we may add a button like "Update comment" after "Add note" with the same look or something.

**Comment by satterly** [comment] 2020-01-21 22:29
Closing this issue as duplicate of #235 .

**Closed by satterly** 2020-01-21 22:29 UTC
Labels: enhancement
